# Generated by Django 3.2.8 on 2021-11-06 23:54

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
from django.db import migrations, models
import django.db.models.deletion
from bascula.models import Usuario


def createAdmin(apps, schema_editor):
    user = Usuario(
        username = 'admin',
        email = 'admin@admin.com',
        first_name = 'Admin',
        last_name = 'User',
    )
    user.set_password("123456")
    user.is_superuser = True
    user.is_staff = True
    user.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destinos',
            },
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('costo_tonelada', models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='El costo de la tonelada no puede ser menor a $1')])),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Residuo',
                'verbose_name_plural': 'Residuos',
                'db_table': 'residuos',
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('nombre_fantasia', models.CharField(max_length=255, unique=True)),
                ('cuit', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de cuit inválido', regex='^(20|23|24|25|26|27|30|33|34)(-)(\\D)?[0-9]{8}(-)(\\D)?[0-9]$')])),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'transportistas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pesaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generador', models.CharField(max_length=255)),
                ('residuo', models.CharField(max_length=255)),
                ('transportista', models.CharField(max_length=255)),
                ('camion', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('pesaje', models.FloatField()),
                ('costo', models.FloatField()),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to='bascula.usuario')),
            ],
            options={
                'verbose_name': 'Pesaje',
                'verbose_name_plural': 'Pesajes',
                'db_table': 'pesajes',
            },
        ),
        migrations.CreateModel(
            name='Generador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('nombre_fantasia', models.CharField(max_length=255, unique=True)),
                ('cuit', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de cuit inválido', regex='^(20|23|24|25|26|27|30|33|34)(-)(\\D)?[0-9]{8}(-)(\\D)?[0-9]$')])),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('residuos', models.ManyToManyField(to='bascula.Residuo')),
            ],
            options={
                'verbose_name': 'Generador',
                'verbose_name_plural': 'Generadores',
                'db_table': 'generadores',
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=7, unique=True)),
                ('tara', models.FloatField()),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('transportista', models.ForeignKey(db_column='codigo_transportista', on_delete=django.db.models.deletion.PROTECT, to='bascula.transportista', to_field='codigo')),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camiones',
                'db_table': 'camiones',
            },
        ),
        migrations.RunPython(createAdmin),            
    ]
