# Generated by Django 3.2.8 on 2021-11-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('admin', models.BooleanField(default=False)),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destinos',
            },
        ),
        migrations.CreateModel(
            name='Generador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_fantasia', models.CharField(max_length=255)),
                ('cuit', models.CharField(max_length=13)),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Generador',
                'verbose_name_plural': 'Generadores',
                'db_table': 'generadores',
            },
        ),
        migrations.CreateModel(
            name='Pesaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('generador', models.CharField(max_length=255)),
                ('residuo', models.CharField(max_length=255)),
                ('transportista', models.CharField(max_length=255)),
                ('camion', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('id_usuario', models.CharField(max_length=255)),
                ('pesaje', models.FloatField()),
                ('costo', models.FloatField()),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pesaje',
                'verbose_name_plural': 'Pesajes',
                'db_table': 'pesajes',
            },
        ),
        migrations.CreateModel(
            name='Residuo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('costo_tonelada', models.FloatField()),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Residuo',
                'verbose_name_plural': 'Residuos',
                'db_table': 'residuos',
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_fantasia', models.CharField(max_length=255)),
                ('cuit', models.CharField(max_length=13)),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'transportistas',
            },
        ),
        migrations.CreateModel(
            name='GeneradoresResiduos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('generador', models.ForeignKey(db_column='id_generador', on_delete=django.db.models.deletion.PROTECT, to='bascula.generador')),
                ('residuo', models.ForeignKey(db_column='id_residuo', on_delete=django.db.models.deletion.PROTECT, to='bascula.residuo')),
            ],
            options={
                'verbose_name': 'GeneradoresResiduos',
                'verbose_name_plural': 'GeneradoresResiduos',
                'db_table': 'generadores_residuos',
            },
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=7)),
                ('tara', models.FloatField()),
                ('fcreacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('transportista', models.ForeignKey(db_column='codigo_transportista', on_delete=django.db.models.deletion.PROTECT, to='bascula.transportista', to_field='codigo')),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camiones',
                'db_table': 'camiones',
            },
        ),
    ]
