# Generated by Django 3.2.8 on 2021-11-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bascula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
